branch-defaults:
  eb:
    environment: usac-dev
    group_suffix: null
environment-defaults:
  usac-database:
    branch: null
    repository: null
global:
  application_name: usac
  branch: null
  default_ec2_keyname: aws-eb-usac
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
